workspace:
  base: /mdbook

pipeline:
  nix:
    image: nixos/nix
    environment:
      - NIX_CONFIG=experimental-features = nix-command flakes
    commands:
      - nix flake check
      - nix build '.#mdbook-toc'
      - nix build '.#docker'
      - mv result result.tar.gz
      - cp result.tar.gz result
  debug:
    image: nixos/nix
    commands:
      - ls -la
  publish:
    image: git.0x76.dev/v/push-container:0.1.0
    settings:
      username: v
      password:
        from_secret: registry_password
      repo: git.0x76.dev
      image: git.0x76.dev/v/mdbook-dockerfile
      tag: 0.1.0
