pipeline:
  nix:
    image: nixos/nix
    environment:
      - NIX_CONFIG=experimental-features = nix-command flakes
    commands:
      - nix flake check
      - nix build '.#mdbook-toc'
      - nix build '.#docker'

