workspace:
  base: /mdbook

pipeline:
  nix:
    image: nixos/nix
    environment:
      - NIX_CONFIG=experimental-features = nix-command flakes
    commands:
      - nix flake check
      - nix build '.#mdbook-toc'
      - nix build '.#docker'
      - cp result image.tar.gz
  publish:
    image: git.0x76.dev/v/push-container:0.2.0
    settings:
      username: v
      password:
        from_secret: registry_password
      repo: git.0x76.dev
      image: v/mdbook-container
      tag: 0.1.0
