pipeline:
  nix:
    image: nixos/nix
    environment:
      - NIX_CONFIG=experimental-features = nix-command flakes
    commands:
      - nix flake check
      - nix build '.#mdbook-toc'
  publish:
    image: git.0x76.dev/v/push-nix-container:main
    settings:
      username: v
      password:
        from_secret: registry_password
      package: container # nix os package to build
      repo: git.0x76.dev
      image: v/mdbook-container
